apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-events-website
  labels:
    app: auto-events-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auto-events-website
  template:
    metadata:
      labels:
        app: auto-events-website
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: karpenter.sh/capacity-type
                    operator: In
                    values:
                      - spot
            - weight: 50
              preference:
                matchExpressions:
                  - key: karpenter.k8s.aws/instance-family
                    operator: In
                    values:
                      - c4
                      - c5
                      - c5a
                      - c5d
                      - c5n
                      - m4
                      - m5
                      - m5a
                      - m5d
                      - m5n
                      - m6a
                      - m6i
      containers:
      - name: events-website
        image: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/events-website:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: API_URL
          value: "http://auto-events-backend-service"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: auto-events-website-service
spec:
  selector:
    app: auto-events-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
