apiVersion: v1
kind: Service
metadata:
  name: events-website-loadbalancer
  labels:
    app: events-website
spec:
  type: LoadBalancer
  selector:
    app: events-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  sessionAffinity: None