apiVersion: v1
kind: Service
metadata:
  name: events-backend-loadbalancer
  labels:
    app: events-backend
spec:
  type: LoadBalancer
  selector:
    app: events-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  sessionAffinity: None