apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: space-invaders-cluster
  region: us-east-1
  version: "1.34"

nodeGroups:
  - name: space-invaders-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
