apiVersion: v1
kind: Service
metadata:
  name: space-invaders-service
spec:
  type: LoadBalancer
  selector:
    app: space-invaders
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
